### ISSUE TITLE
AGVPN's DNS settings have higher priority than AG on Windows

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/VpnLibs#14]
## Steps to reproduce

1. Enable DNS protection in AdGuard for Windows
2. Choose AdGuard DNS server there
3. Start AG VPN
4. Open https://adguard.com/test.html

## Expected result

AdGuard DNS default is used.

## Actual result

AdGuard DNS Non-Filtering is used (which means that AGVPN has overridden DNS settings).

**Comment by sfionov** [comment]
Should be fixed with Wintun
