### ISSUE TITLE
Unable to access intra website by adding it to exclusions list + add the browser to Split tunneling

### ISSUE THREAD

**Issue by MoienBowen** [AdguardTeam/VpnLibs#17]
### Issue Details

- **AdGuard VPN version:**
1.1.0.167 release for macOS
- **VPN mode:**
Regular mode on macOS
- **Device:**
MacBook Pro (14-inch, 2021)
- **Operating system and version:**
macOS 12.3

### Expected Behavior

We have a intranet website abc.com which can be only accessed with our intranet. I added the website into exclusions list and FireFox into split tunneling.
With the VPN turned on, I should be able to access abc.com with FireFox.

### Actual Behavior

Unable to access with VPN turned on.

**Comment by ameshkov** [comment]
There's a chance that the problem is that you need to use your intranet's DNS service to access that website.

**Comment by ameshkov** [comment]
@sfionov what do you think, should we consider adding a logic that uses system DNS for excluded domains?

**Comment by MoienBowen** [comment]
> There's a chance that the problem is that you need to use your intranet's DNS service to access that website.

I can confirm that it does require the intranet's DNS. However, the current public version has no DNS setting, and in the 1.2.0.180 nightly version, even I set the System default option for DNS servers, I am still unable to access those intranet website. (I am connected to our intranet WiFi).

**Comment by ameshkov** [comment]
Well, "System default" is a bug, should be simply "Default", this is rather strange for a VPN service to rely on your ISP's DNS.

I think we should make an exception for "excluded" domains or at least and route them to the system default.

You can try setting your intranet DNS manually there, though.

**Comment by maxikuzmin** [comment]
@n00d1e5 please tell me if the question is still actual?

**Comment by maxikuzmin** [comment]
@n00d1e5 ping

**Comment by MoienBowen** [comment]
> @n00d1e5 please tell me if the question is still actual?

Yes...
The current version is 1.2.3.203 for macOS, I set Firefox for Split tunneling and xxx website (which has particular DNS requirement) in Exclusions. And I cannot access to the website once Adguard VPN is activated.

**Comment by sfionov** [comment]
@ameshkov 

> what do you think, should we consider adding a logic that uses system DNS for excluded domains?

Yes, that's possible. However, additional logic will be needed in DnsLibs to bypass outbound proxy for fallbacks-exclusions.
