### ISSUE TITLE
Windows: TUN/TAP Device

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/VpnLibs#21]
@pancakeufo commented on [Thu Apr 21 2022](https://github.com/AdguardTeam/AdGuardVPNForWindows/issues/255)

- [ YES ] I am running the latest version
- [ YES ] I checked the documentation and found no answer
- [ YES  ] I checked to make sure that this issue has not already been filed

I would like to share my connection over wi-fi to my phone. I can't do it without a TAP device in Windows.

**Comment by mh292929** [comment]
I have the same problem. When the vpn connection is established, vpn cannot be used in windows subsystem for linux and windows subsystem for android.
