### ISSUE TITLE
VPN and HTTP/3 or QUIC traffic

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/VpnLibs#26]
Hello,

VPN does not route HTTP/3 and QUIC traffic? Connecting to my server at HTTP/3 only works when VPN is turned off or a domain/IP address is added to the exclusions. With enabled "QUIC experimental protocol" option nothing works too😐

Thank you.
Best regards🫶🏻

**Comment by ngorskikh** [comment]
Currently, the VPN client blocks QUIC traffic. This is done so that the domain exclusions can work properly.

The QUIC option in the advanced settings refers to the protocol that the client uses to talk to the VPN endpoint, not to the forwarded traffic.

We have plans to add QUIC support.
