### ISSUE TITLE
Exclusions should be resolved using the system DNS server

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/VpnLibs#27]
The problem is that we now use the VPN's DNS server, but we shouldn't do that for exclusions.

**Comment by ngorskikh** [comment]
Note: this should work backwards in `selective` mode: exclusions must be resolved with a trustworthy resolver through the VPN endpoint.
Case in point: in selective mode the domains which should be accessed through the VPN might get resolved to some "blocking" IP address by the system resolver.

**Comment by ameshkov** [comment]
Right, good point
