### ISSUE TITLE
AG VPN for windows does not work with Clumsy / WinDivert

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/VpnLibs#38]

**Comment by ngorskikh** [comment]
@zzebrum I can't repro for myself. Does it work if you try a filter like `outbound and not loopback` in Clumsy? If loopback is broken we can't guarantee anything :)

**Comment by ngorskikh** [comment]
@zzebrum Sorry, I though this was about AdGuard (not VPN)
