### ISSUE TITLE
With Wintun enabled speed is much lower (20-30 Mbits instead of 90 Mbits for default)

### ISSUE THREAD

**Issue by shamarin** [AdguardTeam/VpnLibs#54]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.3.0 nightly 30 build 1413

### Environment

```markdown
- OS:Windows 11 x64 22635.3646
- Other network-level software:
```

### Which DNS server do you use?

Default

### Use Wintun

- [X] yes, I do

### Issue Details

Steps to reproduce:
1. Select Wintun in advanced settings 
2. Connect to the same VPN server

### Expected Behavior

Speed of the internet connection must be the same or a little bit higher due to Wireguard VPN addapter, also there must be no loss of the internet traffic even with heavier load (working torrent client on system)

### Actual Behavior

Speed of the internet connection is much lower (20-30 Mbits and with the default settings without Wintun it's about 90 Mbits as my ISP provides me 100 Mbits speed), also there is some loss of data (packets) and loose of the connection if there is heavier load on internet connection (working torrent client) - in this case sometimes Adguard showing that there is no disconnection, but I can't open any internet resource in my browser (showing no internet connection) and if to reconnect again it will be ok and after some time again.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

### Additional Information

HTTP/3 (QUIC) is enabled and also the same with it disabled.

**Comment by shamarin** [comment]
Torrent client added to exclusions in Adguard VPN

**Comment by ngorskikh** [comment]
@shamarin Hello! Could you please do an experiment to help me make sense of this issue?
1. First, update AdGuard VPN to the latest Nightly version.
2. Go to the exclusions tab and make sure that *no* apps are excluded (VPN is *on* for all apps)
3. Go to the exclusions tab and make sure that VPN is in "selective" mode, and *no* domains are selected. You should see a warning: this is intended behaviour.
4. The configuration should like something like this:
![image](https://github.com/user-attachments/assets/380725ee-23e8-4f8e-b28f-9d0e1ab40803)
![image](https://github.com/user-attachments/assets/501f188f-a298-4fe6-89f5-a8ba0416fb5c)
5. Connect to any endpoint and run `speedtest.net` a few times in both WinTun enabled and WinTun disabled modes. Also take note of the CPU usage of `AdGuardVpnSvc` in both cases. Share the results in this thread.

**Comment by shamarin** [comment]
> [@shamarin](https://github.com/shamarin) Hello! Could you please do an experiment to help me make sense of this issue?
> 
>     1. First, update AdGuard VPN to the latest Nightly version.
> 
>     2. Go to the exclusions tab and make sure that _no_ apps are excluded (VPN is _on_ for all apps)
> 
>     3. Go to the exclusions tab and make sure that VPN is in "selective" mode, and _no_ domains are selected. You should see a warning: this is intended behaviour.
> 
>     4. The configuration should like something like this:
>        ![image](https://github.com/user-attachments/assets/380725ee-23e8-4f8e-b28f-9d0e1ab40803)
>        ![image](https://github.com/user-attachments/assets/501f188f-a298-4fe6-89f5-a8ba0416fb5c)
> 
>     5. Connect to any endpoint and run `speedtest.net` a few times in both WinTun enabled and WinTun disabled modes. Also take note of the CPU usage of `AdGuardVpnSvc` in both cases. Share the results in this thread.

Did it.
With no exclusions with the latest nightly build (2.6.0 nightly 30) problem is only with Total Commander (WebDav plugin). On Total Commander upload speed is only 30 Mbits with default HTTP/2 and with QUIC. If Total commander is in exclusions then speed is fast.

**Comment by shamarin** [comment]
With today nightly build just the same problem on WebDav plugin Total Commander

![Image](https://github.com/user-attachments/assets/425e3517-5813-468e-9892-40f68a8b5933)

**Comment by shamarin** [comment]
Without VPN connection

![Image](https://github.com/user-attachments/assets/5b606b5e-2957-4576-9b96-cdc4cb969a9c)

**Comment by shamarin** [comment]
Seams that now exclusions doesn't work any more. Speed is just the same if Total Commander is in exclusions.

**Comment by shamarin** [comment]
Problem only exist with Wintun. With WFP exclusions works normally and without exclusion Total Commander speed is full on upload.

**Comment by shamarin** [comment]
![Image](https://github.com/user-attachments/assets/75c013a1-a667-4587-875c-ae57d23487f3)

**Comment by shamarin** [comment]
Maybee this issue https://github.com/AdguardTeam/VpnLibs/issues/62 is correlated with that.
