### ISSUE TITLE
Intercepting ICMP in tunnel mode

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/VpnLibs#9]
In the current version of VpnLibs, we don't intercept ICMP at all. The root cause of it is the network driver, we just don't intercept ICMP at the moment.

**Comment by RalMay** [comment]
I case that is possible:
Intercept at network layer, not at transport layer, and you have all traffic handled - Internet is a plain IP based protocol.

edit: mixed up L2 and L3 names, sorry.

**Comment by sxgunchenko** [comment]
vpn-client/pull-requests/286
